name: Deploy IaC

on:
  workflow_call:
    outputs:
      value: ${{ github.event.inputs.resources }}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-iac
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      resources: ${{ steps.pulumi-output.outputs.resources }}
    defaults:
      run:
        working-directory: iac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev
          work-dir: iac
          cloud-url: ${{ secrets.PULUMI_CLOUD_URL }}
          secrets-provider: pathphrase

      - name: Pulumi Output
        id: pulumi-output
        run: |-
          RESOURCES=$(pulumi stack --stack dev output --json)
          echo $RESOURCES
          {
            echo 'resources<<EOF'
            echo $RESOURCES
            echo EOF
          } >> "$GITHUB_OUTPUT"
