name: Helm Package


on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: string
        required: true


jobs:

