name: Production Deploy


on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-production
  cancel-in-progress: true


jobs:
  call-docker-build-push:
    name: Docker Build and Push
    uses: ./.github/workflows/docker-build-push.yaml
    secrets: inherit

  call-helm-package:
    name: Deploy Frontend
    needs: call-docker-build-push
    uses: ./.github/workflows/deploy-frontend.yaml
    secrets: inherit
    with:
      IMAGE_TAG: ${{ needs.call-deploy-iac.outputs.image }}
