name: CI


on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yaml'
      - '.github/workflows/lint.yaml'
      - '.github/workflows/npm-build.yaml'
      - '.github/workflows/docker-build.yaml'
      - '.github/workflows/deploy.yaml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-frontend


jobs:
  call-lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    secrets: inherit

  call-npm-build:
    name: Frontend Build
    needs: call-lint
    uses: ./.github/workflows/npm-build.yaml
    secrets: inherit

  call-docker-build:
    name: Docker Build
    needs: call-lint
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      TAG: latest

  call-deploy:
    name: Deploy GitHub Pages
    needs: call-npm-build
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
