name: CI


on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yaml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-frontend


jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  call-frontend-build:
    name: Frontend Build
    needs: lint
    uses: ./.github/workflows/frontend-build.yaml
    secrets: inherit

  lint-iac:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
