name: Cloud Production Deploy


on:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
      - '.github/workflows/cloud.yaml'
      - '.github/workflows/cloud-lint.yaml'
      - '.github/workflows/cloud-stack-deploy.yaml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cloud-production
  cancel-in-progress: true


jobs:
  call-cloud-lint:
    name: Cloud Lint
    uses: ./.github/workflows/cloud-lint.yaml
    secrets: inherit

  call-cloud-stack-deploy:
    name: Cloud Stack Deploy
    needs: call-cloud-lint
    uses: ./.github/workflows/cloud-stack-deploy.yaml
    secrets: inherit
