name: Cloud Production Deploy


on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cloud-production
  cancel-in-progress: true


jobs:
  call-cloud-stack-deploy:
    name: Cloud Stack Deploy
    uses: ./.github/workflows/cloud-stack-deploy.yaml
    secrets: inherit

  call-frontend-s3-upload:
    name: Frontend S3 Build
    needs: call-cloud-stack-deploy
    uses: ./.github/workflows/frontend-s3-upload.yaml
    secrets: inherit
    with:
      BUCKET_NAME: ${{ fromJson(needs.call-cloud-stack-deploy.outputs.resources).resources.bucketName }}
