name: Cloud Stack Deploy


on:
  workflow_call:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-iac
  cancel-in-progress: true


jobs:
  cloud-stack-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev
          work-dir: iac
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
