name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_S3_BUCKET: portfolio-bucket-innokentii
  AWS_REGION: ams3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build ReactJS Application
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload build to DigitalOcean Spaces Object Storage
        uses: BetaHuhn/do-spaces-action@v2
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          SOURCE_DIR: 'frontend/build'