name: Fronetnd S3 Build and Upload

on:
  workflow_dispatch:

env:
  SPACE_NAME: portfolio-bucket-innokentii
  SPACE_REGION: ams3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build ReactJS Application
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload build to DigitalOcean Spaces Object Storage
        uses: BetaHuhn/do-spaces-action@v2
        env:
          space_name: ${{ env.SPACE_NAME }}
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
          space_region: ${{ env.SPACE_REGION }}
          source: frontend/build
          out_dir: build