name: Production Deploy


on:
  push:
    tags:
      - 'v*'


env:
  HELM_PACKAGES_REPO: helm-packages


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-production
  cancel-in-progress: true


jobs:
  call-docker-build-push:
    name: Docker Build and Push
    uses: ./.github/workflows/docker-build-push.yaml
    secrets: inherit
    with:
      TAG: ${{ github.ref_name }}

  call-update-helm-package:
    name: Update Helm Package
    needs: call-docker-build-push
    uses: ${{ github.repository_owner }}/${{ env.HELM_PACKAGES_REPO }}.github/workflows/update-helm-package.yaml
    secrets: inherit
    with:
      PROJECT_NAME: ${{ github.repository }}
      IMAGE_TAG:  ${{ github.ref_name }}
